shared:
    image: node:6
    settings:
        email: daolam112@gmail.com
jobs:
    main:
        environment:
            EMAIL: a@yahoo.com
        steps:
            - echo: echo $SD_ARTIFACTS_DIR
            - save: echo hello > $SD_ARTIFACTS_DIR/hello.txt
            - cat: cat $SD_ARTIFACTS_DIR/hello.txt
            - build: echo $SD_BUILD_ID
            - sd: echo $SD_TOKEN
            - test: curl -X POST -d '{"name": "screwdriver/build","labels": ["stable"],"version": "1.7.3","description": "this is a template","maintainer": "foo@bar.com","config": { "steps": [{"echo": "echo hello"}]}}' -H "Content-Type: application/json" http://192.168.1.101:9001/v4/templates
            - stuff-test: echo hello
            - stuff_test: echo goodbye
