shared:
    image: node:6
    settings:
        email: daolam112@gmail.com
jobs:
    main:
        environment:
            EMAIL: a@yahoo.com
        steps:
            - echo: echo $SD_ARTIFACTS_DIR
            - save: echo hello > $SD_ARTIFACTS_DIR/hello.txt
            - cat: cat $SD_ARTIFACTS_DIR/hello.txt
            - build: echo $SD_BUILD_ID
            - fail: exit 1
